name: 'Build Mochi release with Spack'
description: 'Build the release of a specified Mochi package using Spack'

inputs:
  spack-version:
    description: 'Version of spack to use'
    required: false
    default: 'develop'
  mochi-spack-packages-version:
    description: 'Version or commit hash of the mochi-spack-packages'
    required: false
    default: 'main'
  package-name:
    description: 'Package to build'
    required: false
    default: 'unspecified'
  package-version:
    description: 'Version of the package to build (should start with @)'
    require: false
    default: ''
  build-cache-token:
    description: 'Token to use to push into the build cache'
    required: false
    default: 'unspecified'

runs:
  using: "composite"
  steps:
  - name: Setup spack
    uses: spack/setup-spack@v2.1.1
    with:
      ref: ${{ inputs.spack-version }}

  - name: Extract name of calling repository
    id: extract_repo_name
    if: ${{ inputs.package == 'unspecified' }}
    shell: bash
    run: |
      REPO_NAME=$(echo "${GITHUB_REPOSITORY}" | cut -d'/' -f2)
      echo "::set-output name=repo_name::$REPO_NAME"

  - name: Find the package name
    id: determine_name
    shell: bash
    run: |
      if [[ "${{ inputs.package-name }}" == "unspecified" ]]; then
        PACKAGE_NAME="${{ steps.extract_repo_name.outputs.repo_name }}"
      else
        PACKAGE_NAME="${{ inputs.package-name }}"
      fi
      echo "::set-output name=package_name::$PACKAGE_NAME"

  - name: Add mochi-spack-packages
    shell: bash
    run: |
      git clone https://github.com/mochi-hpc/mochi-spack-packages
      pushd mochi-spack-packages
      git checkout ${{ inputs.mochi-spack-packages-version }}
      popd
      spack -e "$GITHUB_ACTION_PATH" repo add mochi-spack-packages

  - name: Add package to environment
    shell: bash
    run: |
      spack -e "$GITHUB_ACTION_PATH" add \
          ${{ steps.determine_name.outputs.package_name }}${{ inputs.package-version }}

  - name: Install environment
    shell: bash
    run: |
      spack -e "$GITHUB_ACTION_PATH" install

  - name: Push packages to buildcache and update index
    if: ${{ inputs.build-cache-token != 'unspecified' }}
    shell: bash
    run: |
      spack -e "$GITHUB_ACTION_PATH" mirror set --push \
            --oci-username ${{ github.actor }} \
            --oci-password "${{ inputs.build-cache-token }}" mochi-buildcache
      spack -e "$GITHUB_ACTION_PATH" buildcache push --base-image ubuntu:22.04 \
            --unsigned --only dependencies --update-index mochi-buildcache
